# Run this with
# docker-compose -f docker-compose-demo.yml up -d

services:
  qc-snapshot-api:
    build:
      context: .
      dockerfile: Dockerfile.demo
    image: qc-snapshot:latest
    container_name: mes-qc-summary-dev-demo
    ports:
      - "8100:8000"
    env_file:
      - .env.demo
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  qc-snapshot-worker:
    image: qc-snapshot:latest
    container_name: mes-qc-snapshot-worker-dev-demo
    env_file:
      - .env.demo
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    command: ["python", "-u", "scripts/insert_snapshot_from_mongo.py"]
    restart: unless-stopped
